import 'package:flutter/foundation.dart';
import '../models/admin_client.dart';
import '../models/managed_service.dart';
import 'supabase_service.dart';

class AdminDataService extends ChangeNotifier {
  List<AdminClient> _clients = [];
  List<ManagedService> _services = [];

  AdminDataService() {
    _loadData();
  }

  Future<void> _loadData() async {
    try {
      _services = await SupabaseService.getServices();
      
      final clientData = await SupabaseService.getClients();
      _clients = clientData.map((c) => AdminClient(
        id: c['id_usuario'].toString(),
        name: c['nombre'] ?? 'Sin nombre',
        email: c['correo'] ?? 'Sin correo',
        phone: c['telefono'] ?? 'Sin telefono',
      )).toList();

      notifyListeners();
    } catch (e) {
      debugPrint('Error cargando datos de Supabase (Admin): $e');
    }
  }

  List<AdminClient> get clients => List.unmodifiable(_clients);
  List<ManagedService> get services => List.unmodifiable(_services);
  List<ManagedService> get activeServices => List.unmodifiable(_services.where((service) => service.active));

  Future<void> saveClient(AdminClient client) async {
    try {
      final index = _clients.indexWhere((item) => item.id == client.id);
      if (index == -1) {
        // Assume ID generated by Supabase
        await SupabaseService.addClient(client.name, client.email, client.phone);
      } else {
        await SupabaseService.updateClient(client.id, client.name, client.email, client.phone);
      }
      await _loadData();
    } catch (e) {
      debugPrint('Error guardando cliente: $e');
    }
  }

  Future<void> deleteClient(String id) async {
    try {
      await SupabaseService.deleteClient(id);
      await _loadData();
    } catch (e) {
      debugPrint('Error eliminando cliente: $e');
    }
  }

  Future<void> saveService(ManagedService service) async {
    try {
      final index = _services.indexWhere((item) => item.id == service.id);
      if (index == -1) {
        await SupabaseService.addService(service.name, service.description, service.price, service.active);
      } else {
        await SupabaseService.updateService(service.id, service.name, service.description, service.price, service.active);
      }
      await _loadData();
    } catch (e) {
      debugPrint('Error guardando servicio: $e');
    }
  }

  Future<void> deleteService(String id) async {
    try {
      await SupabaseService.deleteService(id);
      await _loadData();
    } catch (e) {
      debugPrint('Error eliminando servicio: $e');
    }
  }
}
